<?php
/**
 * @var Klevu\Categorynavigation\Block\CategoryDisplay\ThemeV2 $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$contentMinHeight = $block->getContentMinHeight();
?>

<?php if ($contentMinHeight): ?>
    <?= $secureRenderer->renderTag(
        'style',
        [
            'type' => 'text/css',
        ],
        '.klevuLanding{min-height: ' . /** @noEscape */ $contentMinHeight .'px;}',
        true
    ) ?>
<?php endif; ?>
<div class="klevuLanding"></div>
