<?php
/**
 * @var \Klevu\Categorynavigation\Block\Product\Tracking $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php if ($block->isExtensionConfigured() && $block->checkPreserveLayout()) { ?>
    <?php $jsonTrackingData = $block->getJsonTrackingData();?>
    <?php if ($jsonTrackingData) { ?>
        <?php
        $scriptString = <<<script

    document.addEventListener("DOMContentLoaded", function() {
        try {
            var counter = 0;
            var timeKlevuUpdate = setInterval(function () {
                var elem = document.getElementById('klevu_sessionId');
                if (elem !== null && elem.innerHTML) {
                    categoryAnaylticsProductClickKlevu();
                    clearInterval(timeKlevuUpdate);
                } else {
                    counter++;
                    if (counter > 7) {
                        categoryAnaylticsProductClickKlevu();
                        clearInterval(timeKlevuUpdate);
                    }
                }
            }, 700);
        } catch (e) {
            console.error(e);
        }
    });

    function categoryAnaylticsProductClickKlevu() {
        let cats;
        try {
            cats = JSON.parse(localStorage.getItem("categories"));
        } catch (e) {
            cats = null;
        }
        const url = (document.referrer !== "") ? (new URL(document.referrer)) : null;
        if (url === null || cats === null) {
            return;
        }
        if (cats[url.pathname]) {
            klevu_search_product_tracking = {$jsonTrackingData};
            klevu_search_product_tracking.klevu_categoryName = cats[url.pathname].name;
            klevu_search_product_tracking.klevu_categoryPath = cats[url.pathname].categoryPath;
            if(document.getElementById('klevu_loginCustomerEmail')) {
                klevu_search_product_tracking.klevu_loginCustomerEmail = document.getElementById('klevu_loginCustomerEmail').innerHTML;
            }
            if(document.getElementById('klevu_sessionId')) {
                klevu_search_product_tracking.klevu_sessionId = document.getElementById('klevu_sessionId').innerHTML;
            }

            var klevu_cat_productIds = localStorage.getItem("klevu_cat_productIds_" + encodeURIComponent(klevu_search_product_tracking.klevu_categoryName));
            var klevu_page_startsfrom = localStorage.getItem("klevu_page_startsfrom");
            var ids = (klevu_cat_productIds == null) ? [] : klevu_cat_productIds.split(",");
            var product_position = ids.indexOf(klevu_search_product_tracking.klevu_productId) + 1;
            product_position += parseInt(klevu_page_startsfrom);

            klevu_search_product_tracking.klevu_productPosition = product_position;

            if (klevu_search_product_tracking.klevu_productId !== localStorage.getItem("klevu_product_call_sent")) {
                const fetchUrl = '{$block->escapeUrl($block->getCategoryNavigationTrackingUrl($block->getStoreId()))}'
                 + '?' + convertDataToUrlParams(klevu_search_product_tracking);

                fetch(fetchUrl, {
                    method: 'GET',
                    crossDomain: true
                }).then(response => {
                    localStorage.setItem("klevu_product_call_sent", klevu_search_product_tracking.klevu_productId);
                });

                function convertDataToUrlParams(data) {
                    let params = [];
                    for (let key in data) {
                        if (data.hasOwnProperty(key)) {
                            params.push(key + '=' + encodeURIComponent(data[key]));
                        }
                    }
                    params = params.join('&');
                    return params;
                }
            }
        }
    }

script;
        ?>
        <?= $secureRenderer->renderTag(
            'script',
            ['type' => 'text/javascript'],
            $scriptString,
            false
        ) ?>
    <?php } ?>
<?php } ?>
