<?php /** @var \Klevu\Categorynavigation\Block\Product\Tracking $block */ ?>
<?php if ($block->isExtensionConfigured() && !empty($block->getCategoryName()->getName())) { ?>
    <?php if ($block->checkPreserveLayout()) { ?>
        <script type="text/javascript">
            require(['jquery'], function () {
                try {
                    klevu_search_product_tracking = <?php echo $block->getJsonTrackingData() ?>;
                    var klevu_cat_productIds = localStorage.getItem("klevu_cat_productIds");
                    var klevu_page_startsfrom =  localStorage.getItem("klevu_page_startsfrom");
                    var ids = klevu_cat_productIds.split(",");
                    var product_position =  ids.indexOf(klevu_search_product_tracking.klevu_productId) + 1;
                    product_position = product_position = product_position + parseInt(klevu_page_startsfrom);
                    klevu_search_product_tracking.klevu_productPosition = product_position;
                    var param = jQuery.param(klevu_search_product_tracking);

                    if(klevu_search_product_tracking.klevu_productId != localStorage.getItem("klevu_product_call_sent")) {
                        jQuery.ajax({
                            url: '//<?php echo $block->getCategoryNavigationTrackingUrl($block->getStoreId()) ?>/analytics/categoryProductClickTracking',
                            type: 'GET',
                            data: param,
                            dataType: 'json',
                            statusCode: {
                                200: function (data) {
                                    localStorage.setItem("klevu_product_call_sent", klevu_search_product_tracking.klevu_productId);
                                }
                            },
                            timeout: 3000,
                            crossDomain: true
                        });
                    }
                } catch (e) {
                    console.log(e);
                }
            });
        </script>
    <?php } ?>
<?php } ?>