<?php
/**
 * @var Klevu\Categorynavigation\Block\Html\Head\ThemeV2\AddPriceSuffixToQuery $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
$scriptString = <<<script

    klevu.settings.chains.initChain.add({
        name: "addPriceSuffixToCatNavQuery",
        fire: function (data) {
            if (klevu.getObjectPath(klevu.search, "catnav", false)
                && klevu.getGlobalSetting("flags.addPriceSuffixToQuery.catnav", false)
                && typeof klevu_addPriceSuffixToQueryControl === "object"
            ) {
                klevu.search.catnav.getScope().chains.request.control.addAfter('initRequest', klevu_addPriceSuffixToQueryControl);
                klevu.setObjectPath(data, "flags.addPriceSuffixToQuery.catnav", false);
            }
        }
    });

    document.addEventListener('{$block->getCustomerDataLoadErrorEventName()}', function () {
        klevu({ powerUp: { catnav: true }});
    });
    document.addEventListener('{$block->getCustomerDataLoadedEventName()}', function () {
        klevu({
            powerUp: {
                catnav: true
            },
            flags: {
                addPriceSuffixToQuery: {
                    catnav: true
                }
            }
        });
    });

script;
?>
<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    $scriptString,
    false
) ?>
