<?php
/**
 * @var Klevu\Categorynavigation\Block\Html\Head\ThemeV2\AddPriceSuffixToQuery $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
$scriptStringChains = "
    klevu.settings.chains.initChain.add({
        name: 'addPriceSuffixToCatNavQuery',
        fire: function (data) {
            if (klevu.getObjectPath(klevu.search, 'catnav', false)
                && klevu.getGlobalSetting('flags.addPriceSuffixToQuery.catnav', false)
                && typeof klevu_addPriceSuffixToQueryControl === 'object'
            ) {
                klevu.search.catnav.getScope().chains.request.control.addAfter('initRequest', klevu_addPriceSuffixToQueryControl);
                klevu.setObjectPath(data, 'flags.addPriceSuffixToQuery.catnav', false);
            }
        }
    });";
?>

<?php
$catNavPowerUp = "
klevu({ powerUp: { catnav: true }});
";

$catNavPowerUpWithSuffix = "
klevu({
    powerUp: { catnav: true },
    flags: {
        addPriceSuffixToQuery: {
            catnav: true
        }
    }
});";
?>

<?php if ($block->isDeferJs()): ?>
    <?php
    $scriptString = "
        window._klvReady = window._klvReady || [];
        window._klvReady.push(function() {
            {$scriptStringChains}
        });

        var klevuPowerUpCatNav = function() {
            window._klvReady = window._klvReady || [];
            window._klvReady.push(function() {
               {$catNavPowerUp}
            });

            return true;
        };
        var klevuPowerUpCatNavWithSuffix = function () {
            window._klvReady = window._klvReady || [];
            window._klvReady.push(function() {
               {$catNavPowerUpWithSuffix}
            });

            return true;
        };";
    ?>
<?php else: ?>
    <?php
    $scriptString = "
        {$scriptStringChains}

        var klevuPowerUpCatNav = function() {
            {$catNavPowerUp}

            return true;
        };
        var klevuPowerUpCatNavWithSuffix = function () {
            {$catNavPowerUpWithSuffix}

            return true;
        };";
    ?>
<?php endif; ?>

<?php
$scriptString .= "
    document.addEventListener('{$block->getCustomerDataLoadErrorEventName()}', function () {
        klevuPowerUpCatNav();
    });
    document.addEventListener('{$block->getCustomerDataLoadedEventName()}', function () {
        klevuPowerUpCatNavWithSuffix();
    });";
?>

<?= $secureRenderer->renderTag(
    'script',
    [
        'type' => 'text/javascript',
        'id' => 'klevu_catnav_pricesuffix',
    ],
    $scriptString,
    false
) ?>
