<?php
/**
 * @var Klevu\Categorynavigation\Block\Html\Head\ThemeV2\InlineCurrencyTranslation $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
$scriptString = <<<script

    klevu.settings.chains.initChain.add({
        name: "addCurrencyTranslationToCatnav",
        fire: function (data) {
            if (!klevu.getObjectPath(klevu.search, "catnav", false)
                || klevu.search.catnav.getScope().chains.response.success.indexOf("processQuery") <= 0
                || klevu.getGlobalSetting("flags.currencyTranslationAdded.catnav", false)
            ) {
                return;
            }

            klevu.search.catnav.getScope().chains.response.success.addAfter("processQuery", {
                name: "addCurrencyTranslation",
                fire: function (data, scope) {
                    klevu.search.modules.mageConvertPriceRecordCurrencyData(
                        klevu.getObjectPath(data, "template.query.productList.result"),
                        klevu_currentCurrencyCode,
                        klevu_currentCurrencyRates
                    );
                }
            });
            klevu.setObjectPath(data, "flags.currencyTranslationAdded.catnav", true);
        }
    });

script;
?>
<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    $scriptString,
    false
) ?>
