<?php
/**
 * @var Klevu\Categorynavigation\Block\Html\Head\JsAdditional $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
$scriptString = "
    var klevu_pageCategory = '{$block->escapeJsQuote($block->getFullCategoryPath())}';
    sessionStorage.setItem('klevu_pageCategory', klevu_pageCategory);
";
?>
<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    $scriptString,
    false
) ?>
