<?php
/**
 * @var Klevu\Categorynavigation\Block\Html\Head\JsAdditional $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
$scriptString = <<<script

    var klevu_pageCategory = '{$block->escapeJsQuote($block->getFullCategoryPath())}';
    sessionStorage.setItem("klevu_pageCategory", klevu_pageCategory);

script;
?>
<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    $scriptString,
    false
) ?>
